-- MySQL Script generated by MySQL Workbench
-- Tue Nov 30 22:30:25 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Papelplot
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Papelplot
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usuarios` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `primerNombre` VARCHAR(45) NOT NULL,
  `segundoNombre` VARCHAR(45) NULL,
  `primerApellido` VARCHAR(45) NULL,
  `segundoApellido` VARCHAR(45) NULL,
  `correo` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `esAdmin` TINYINT NULL,
  `telefono` DOUBLE NULL,
  PRIMARY KEY (`idUsuario`),
  UNIQUE INDEX `correo_UNIQUE` (`correo` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `articulos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `articulos` (
  `idArticulo` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `precio` DOUBLE NULL,
  `descripcion` VARCHAR(100) NULL,
  `imagen` VARCHAR(500) NULL,
  `existencia` INT NULL,
  PRIMARY KEY (`idArticulo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `metodosPagos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `metodosPagos` (
  `idMetodoPago` INT NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(45) NOT NULL,
  `Detalles` VARCHAR(200) NULL,
  PRIMARY KEY (`idMetodoPago`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ventas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ventas` (
  `idVenta` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATE NOT NULL,
  `idusuario` INT NOT NULL,
  `idmetodoPago` INT NOT NULL,
  PRIMARY KEY (`idVenta`),
  INDEX `fk_Compras_usuarios_idx` (`idusuario` ASC) ,
  INDEX `fk_Compras_metodosPagos1_idx` (`idmetodoPago` ASC) ,
  CONSTRAINT `fk_Compras_usuarios`
    FOREIGN KEY (`idusuario`)
    REFERENCES `usuarios` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Compras_metodosPagos1`
    FOREIGN KEY (`idmetodoPago`)
    REFERENCES `metodosPagos` (`idMetodoPago`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `calificaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `calificaciones` (
  `idUsuario` INT NOT NULL,
  `idArticulo` INT NOT NULL,
  `calificacion` INT NULL,
  `apreciacion` VARCHAR(200) NULL,
  PRIMARY KEY (`idUsuario`, `idArticulo`),
  INDEX `fk_Calificacion_articulos1_idx` (`idArticulo` ASC) ,
  CONSTRAINT `fk_Calificacion_usuarios1`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `usuarios` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Calificacion_articulos1`
    FOREIGN KEY (`idArticulo`)
    REFERENCES `articulos` (`idArticulo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `comentario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `comentario` (
  `idComentario` INT NOT NULL AUTO_INCREMENT,
  `idUsuario` INT NOT NULL,
  `idArticulo` INT NOT NULL,
  `comentario` VARCHAR(200) NULL,
  PRIMARY KEY (`idComentario`, `idUsuario`, `idArticulo`),
  INDEX `fk_comentario_usuarios1_idx` (`idUsuario` ASC) ,
  INDEX `fk_comentario_articulos1_idx` (`idArticulo` ASC) ,
  CONSTRAINT `fk_comentario_usuarios1`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `usuarios` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comentario_articulos1`
    FOREIGN KEY (`idArticulo`)
    REFERENCES `articulos` (`idArticulo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `carritos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `carritos` (
  `idUsuario` INT NOT NULL,
  `idArticulo` INT NOT NULL,
  `cantidad` INT NULL,
  PRIMARY KEY (`idUsuario`, `idArticulo`),
  INDEX `fk_carritos_articulos1_idx` (`idArticulo` ASC) ,
  CONSTRAINT `fk_carritos_usuarios1`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `usuarios` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_carritos_articulos1`
    FOREIGN KEY (`idArticulo`)
    REFERENCES `articulos` (`idArticulo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `contedidoCompras`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `contedidoCompras` (
  `idVenta` INT NOT NULL,
  `idArticulo` INT NOT NULL,
  `cantidad` INT NULL,
  PRIMARY KEY (`idVenta`, `idArticulo`),
  INDEX `fk_contedidoCompras_articulos1_idx` (`idArticulo` ASC) ,
  CONSTRAINT `fk_contedidoCompras_compras1`
    FOREIGN KEY (`idVenta`)
    REFERENCES `ventas` (`idVenta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_contedidoCompras_articulos1`
    FOREIGN KEY (`idArticulo`)
    REFERENCES `articulos` (`idArticulo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `categorias` (
  `idCategoria` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCategoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `categoriasArticulos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `categoriasArticulos` (
  `idCategoria` INT NOT NULL,
  `idArticulo` INT NOT NULL,
  PRIMARY KEY (`idCategoria`, `idArticulo`),
  INDEX `fk_categoriasArticulos_articulos1_idx` (`idArticulo` ASC) ,
  CONSTRAINT `fk_categoriasArticulos_categorias1`
    FOREIGN KEY (`idCategoria`)
    REFERENCES `categorias` (`idCategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_categoriasArticulos_articulos1`
    FOREIGN KEY (`idArticulo`)
    REFERENCES `articulos` (`idArticulo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `compras`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `compras` (
  `idCompra` INT NOT NULL AUTO_INCREMENT,
  `idArticulo` INT NOT NULL,
  `fecha` DATE NOT NULL,
  `cantidad` INT NOT NULL,
  `detalles` VARCHAR(45) NULL,
  PRIMARY KEY (`idCompra`),
  INDEX `fk_compras_articulos1_idx` (`idArticulo` ASC) ,
  CONSTRAINT `fk_compras_articulos1`
    FOREIGN KEY (`idArticulo`)
    REFERENCES `articulos` (`idArticulo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
